[tool.black]
line-length = 100
target-version = ["py310","py311"]

[tool.isort]
profile = "black"
line_length = 100

[tool.ruff]
line-length = 100
extend-exclude = ["build","dist",".venv","venv"]

[tool.ruff.lint]
select = ["E","F","I","W","B","UP"]
ignore = ["E203","E501"]

[tool.mypy]
python_version = "3.11"
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
strict = true
ignore_missing_imports = true
