model:
  h: { d_model: 512, n_layers: 4, n_heads: 8, ffn_mult: 2 }
  l: { d_model: 768, n_layers: 6, n_heads: 12, ffn_mult: 2 }
  use_cross_attn: false
  use_film: true
  act: { max_steps: 3, ponder_cost: 0.01 }
losses:
  portfolio: { enabled: false, weight: 0.1, objective: sharpe, alpha: 0.05 }
  gradnorm: { enabled: false, alpha: 0.5, weight: 0.01 }
