name: CI
on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ "*" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10","3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/ci-requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install minimal deps for CI
      run: |
        python -m pip install --upgrade pip
        pip install -r ci-requirements.txt

    - name: Ruff (lint & format check)
      run: |
        ruff check lab_v10/src --fix
        ruff format lab_v10/src --check

    - name: Mypy (non-blocking)
      run: mypy lab_v10/src --ignore-missing-imports || true

    - name: Bandit (non-blocking)
      run: bandit -r lab_v10/src -f json -o bandit-report.json || true

    - name: Unit tests (offline fast set)
      run: |
        cd lab_v10
        pytest -v tests src/tests -m "not integration" --maxfail=1 --disable-warnings

    - name: Upload test artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-artifacts-${{ matrix.python-version }}
        path: |
          bandit-report.json
          ./**/pytest-*.log
